// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	REQUIRE(inputValidate(2, 10) == 0);
}
// tests for exercise 2
TEST_CASE("Ex2", "[example]")
{
	REQUIRE(inputValidate(10, 2) == 1);
}
TEST_CASE("Ex3", "[example]")
{
	REQUIRE(getListprime(2, 10) == 4);
}
TEST_CASE("Ex4", "[example]")
{
	REQUIRE(getListprime(10, 20) == 4);
}